// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig, env } from 'prisma/config'


export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
    // directUrl: conexão SEM pooler (PgBouncer/Neon-pooled não suporta DDL de migrations)
    // Em produção (Render/Neon), defina DIRECT_URL com a URL não-pooled
    // Em dev local, pode ficar sem — DATABASE_URL conecta direto
    ...(process.env.DIRECT_URL ? { directUrl: env('DIRECT_URL') } : {}),
  },
})